### ISSUE TITLE
Compilation issue with 2.4.2

### ISSUE THREAD

**Issue by TerrorSquad** [yireo/magento2-replace-core#12]
I received this message while trying to execute `bin/magento setup:di:compile`

```
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 117.0 MiBPHP Fatal error:  Uncaught Error: Class 'Magento\CustomerImportExport\Model\Import\AbstractCustomer' not found in /var/www/html/vendor/magento/module-customer-finance/Model/Import/Eav/Customer/Finance.php:18
Stack trace:
#0 /var/www/html/vendor/composer/ClassLoader.php(476): include()
#1 /var/www/html/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile('/var/www/html/v...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Magento\\Custome...')
#3 [internal function]: spl_autoload_call('Magento\\Custome...')
#4 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Magento\\Custome...')
#5 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Magento\\Custome...', '/var/www/html/v...')
#6 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract(Object(RecursiveIteratorIte in /var/www/html/vendor/magento/module-customer-finance/Model/Import/Eav/Customer/Finance.php on line 18
```

**Comment by jissereitsma** [comment]
Thanks for posting this issue. Unfortunately, Magento has chosen to release 2.4.2 first to friends and then to the public, and therefore I don't have the ability to actually test for 2.4.2 before it is officially released.

However, the error is actually self-explanatory: Within the module `magento/module-customer-finance` there is a reference to a class `Magento\CustomerImportExport\Model\Import\AbstractCustomer` in the module `magento/module-customer-import-export` which is actually removed by this meta-package. 

Solution: Either skip removing all these packages because you have a need for this new finance module: I can't determine this for you, this is the responsibility of you as a developer / system integrator. Or replace this finance module as well. This new replacement will be included in the next release (https://github.com/yireo/magento2-replace-core/commit/11d45208b3ba6629d5c76d5855177c7327d7b9c5) this afternoon.

**Comment by jissereitsma** [comment]
Release 4.2.1 already.

**Comment by jissereitsma** [comment]
I'm closing this due to inactivity.
